routes/web.php
<?php

Route::get('/token', function () {
   $token = auth()->user()->generateConfirmationToken();

   dd($token);
});

Auth::routes();

Route::get('/', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
    Route::get('/dashboard', 'DashboardController@index');
});

/**
 * Account
*/
Route::group(['prefix' => 'account', 'middleware' => ['auth'], 'as' => 'account.'], function () {
    Route::get('/', 'Account\AccountController@index')->name('index');

    /**
     * Profile
     */
    Route::get('profile', 'Account\ProfileController@index')->name('profile.index');
    Route::post('profile', 'Account\ProfileController@store')->name('profile.store');

    /**
     * Password
     */
    Route::get('password', 'Account\PasswordController@index')->name('password.index');
    Route::post('password', 'Account\PasswordController@store')->name('password.store');
});

/**
 * Account Activation
 */
Route::group(['prefix' => 'activation', 'as' => 'activation.', 'middleware' => ['guest']], function () {
    Route::get('/resend', 'Auth\ActivationResendController@index')->name('resend');
    Route::post('/resend', 'Auth\ActivationResendController@store')->name('resend.store');
    Route::get('/{confirmation_token}', 'Auth\ActivationController@activate')->name('activate');
});

/**
 * Plans
 */
Route::group(['prefix' => 'plans', 'as' => 'plans.'], function () {
    Route::get('/', 'subscription\PlanController@index')->name('index');
    Route::get('/teams', 'subscription\PlanTeamController@index')->name('teams.index');
});

/**
 * Subscription
 */
Route::group(['prefix' => 'subscription', 'as' => 'subscription.', 'middleware' => ['auth.register']], function () {
    Route::get('/', 'subscription\SubscriptionController@index')->name('index');
    Route::post('/', 'subscription\SubscriptionController@store')->name('store');
});

app/Models/ConfirmationToken.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class ConfirmationToken extends Model
{
    public $timestamps = false;

    protected $dates = [
        'expires_at'
    ];

    protected $fillable = [
        'token',
        'expires_at',
    ];

    public static function boot() {
        parent::boot();
        static::creating(function ($token) {
            optional($token->user->confirmationToken)->delete();
        });
    }

    public function getRouteKeyName()
    {
        return 'token';
    }

    public function user() {
        return $this->belongsTo(User::class);
    }

    public function hasExpired() {
        return $this->freshTimestamp()->gt($this->expires_at);
    }
}

app/Models/Plan.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Builder;
use Illuminate\Database\Eloquent\Model;

class Plan extends Model
{
    public function scopeActive(Builder $builder) {
        return $builder->where('active', true);
    }

    public function scopeForUsers(Builder $builder) {
        return $builder->where('teams_enabled', false);
    }

    public function scopeForTeams(Builder $builder) {
        return $builder->where('teams_enabled', true);
    }
}

app/Models/Traits/HasConfirmationTokens.php
<?php

    namespace App\Models\Traits;

    use App\Models\ConfirmationToken;
    use Illuminate\Support\Str;

    trait HasConfirmationTokens {
        public function generateConfirmationToken() {

            $this->confirmationToken()->create([
                'token' => $token = Str::random(200),
                'expires_at' => $this->getConfirmationTokenExpiry(),
            ]);

            return $token;
        }

        protected function getConfirmationTokenExpiry() {
            return $this->freshTimestamp()->addMinutes(10);
        }

        public function confirmationToken() {
            return $this->hasOne(ConfirmationToken::class);
        }
    }

app/Models/User.php
<?php

namespace App\Models;

use App\Models\Traits\HasConfirmationTokens;
use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable, HasConfirmationTokens;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password', 'activated',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];

    public function hasActivated() {
        return $this->activated;
    }

    public function hasNotActivated() {
        return !$this->activated;
    }
}

app/helpers.php
<?php

if(!function_exists('on_page')) {
    function on_page($path) {
       return request()->is($path);
    }
}


if(!function_exists('return_if')) {
    function return_if($condition, $value) {
       if($condition) {
            return $value;
       }
    }
}

app/Http/Controllers/Account/AccountController.php
<?php

namespace App\Http\Controllers\Account;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;

class AccountController extends Controller
{
    public function index() {
        return view('account.index');
    }
}

app/Http/Controllers/Account/PasswordController.php
<?php

namespace App\Http\Controllers\Account;

use App\Http\Controllers\Controller;
use App\Http\Requests\Account\PasswordStoreRequest;
use App\Mail\Account\PasswordUpdated;
use Illuminate\Support\Facades\Mail;

class PasswordController extends Controller
{
    public function index() {
        return view('account.password.index');
    }

    public function store(PasswordStoreRequest $request) {
        $request->user()->update([
            'password' => bcrypt($request->password),
        ]);

        Mail::to($request->user())->send(new PasswordUpdated());

        return redirect()->route('account.index')->withSuccess('Password updated.');
    }
}

app/Http/Controllers/Account/ProfileController.php
<?php

namespace App\Http\Controllers\Account;

use App\Http\Controllers\Controller;
use App\Http\Requests\Account\ProfileStoreRequest;
use Illuminate\Http\Request;


class ProfileController extends Controller
{
    public function index() {
        return view('account.profile.index');
    }

    public function store(ProfileStoreRequest $request) {
        $request->user()->update($request->only('name', 'email'));

        return back()->withSuccess('Account details updated.');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/DashboardController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class DashboardController extends Controller
{
    public function index() {
        return view('dashboard');
    }
}

app/Http/Controllers/HomeController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

class HomeController extends Controller
{
    /**
     * Show the application dashboard.
     *
     * @return \Illuminate\Contracts\Support\Renderable
     */
    public function index()
    {
        return view('home');
    }
}

app/Http/Controllers/Subscription/PlanController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Http\Controllers\Controller;
use App\Models\Plan;
use Illuminate\Http\Request;

class PlanController extends Controller
{
    public function index() {

        $plans = Plan::active()->forUsers()->get();
        return view('subscription.plans.index', compact('plans'));
    }
}

app/Http/Controllers/Subscription/PlanTeamController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Http\Controllers\Controller;
use App\Models\Plan;
use Illuminate\Http\Request;

class PlanTeamController extends Controller
{
    public function index() {

        $plans = Plan::active()->forTeams()->get();
        return view('subscription.plans.teams.index', compact('plans'));
    }
}

app/Http/Controllers/Subscription/SubscriptionController.php
<?php

namespace App\Http\Controllers\Subscription;

use App\Http\Controllers\Controller;
use App\Models\Plan;
use Illuminate\Http\Request;

class SubscriptionController extends Controller
{
    public function index() {
        $plans = Plan::active()->get();

        return view('subscription.index', compact('plans'));
    }

    public function store() {

    }
}

resources/views/dashboard.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Dashboard</div>

                <div class="card-body">
                    @if (session('status'))
                        <div class="alert alert-success" role="alert">
                            {{ session('status') }}
                        </div>
                    @endif

                    You are logged in!
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
   Home
@endsection

resources/views/layouts/app.blade.php
<!doctype html>
<html lang="{{ str_replace('_', '-', app()->getLocale()) }}">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- CSRF Token -->
    <meta name="csrf-token" content="{{ csrf_token() }}">

    <title>{{ config('app.name', 'Laravel') }}</title>

    <!-- Scripts -->
    <script src="{{ asset('js/app.js') }}" defer></script>

    <!-- Fonts -->
    <link rel="dns-prefetch" href="//fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css?family=Nunito" rel="stylesheet">

    <!-- Styles -->
    <link href="{{ asset('css/app.css') }}" rel="stylesheet">
</head>
<body>
    <div id="app">
        @include('layouts.partials._navigation')

        <main class="py-4">
            <div class="container">
                @include('layouts.partials.alerts._alerts')
                @yield('content')
            </div>
        </main>
    </div>
</body>
</html>

resources/views/layouts/partials/_navigation.blade.php
<nav class="navbar navbar-expand-md navbar-light bg-white shadow-sm">
    <div class="container">
        <a class="navbar-brand" href="{{ url('/') }}">
            {{ config('app.name', 'Laravel') }}
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="{{ __('Toggle navigation') }}">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <!-- Left Side Of Navbar -->
            <ul class="navbar-nav mr-auto">

            </ul>

            <!-- Right Side Of Navbar -->
            <ul class="navbar-nav ml-auto">

                @if (Route::has('plans.index'))
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('plans.index') }}">{{ __('Plans') }}</a>
                    </li>
                @endif

                <!-- Authentication Links -->
                @guest
                    <li class="nav-item">
                        <a class="nav-link" href="{{ route('login') }}">{{ __('Login') }}</a>
                    </li>
                    @if (Route::has('register'))
                        <li class="nav-item">
                            <a class="nav-link" href="{{ route('register') }}">{{ __('Register') }}</a>
                        </li>
                    @endif
                @else
                    <li class="nav-item dropdown">
                        <a id="navbarDropdown" class="nav-link dropdown-toggle" href="#" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" v-pre>
                            {{ Auth::user()->name }} <span class="caret"></span>
                        </a>

                        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">

                            @if(Route::has('account.index'))
                                <a class="dropdown-item" href="{{ route('account.index') }}">Account</a>
                            @endif

                            <a class="dropdown-item" href="{{ route('logout') }}"
                               onclick="event.preventDefault();
                                                     document.getElementById('logout-form').submit();">
                                {{ __('Logout') }}
                            </a>

                            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
                                @csrf
                            </form>
                        </div>
                    </li>
                @endguest
            </ul>
        </div>
    </div>
</nav>

resources/views/layouts/partials/alerts/_alerts.blade.php
@if(session()->has('success'))
    @component('layouts.partials.alerts._alerts_component', ['type' => 'success'])
        {{ session('success') }}
    @endcomponent
@endif

@if(session()->has('error'))
    @component('layouts.partials.alerts._alerts_component', ['type' => 'danger'])
        {{ session('error') }}
    @endcomponent
@endif

resources/views/layouts/partials/alerts/_alerts_component.blade.php
<div class="alert alert-{{ $type }} alert-dismissible fade show" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
        <span aria-hidden="true">&times;</span>
    </button>

    {{ $slot }}

</div>

resources/views/subscription/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row justify-content-center">
        <div class="col-md-8">
            <div class="card">
                <div class="card-header">Subscription</div>

                <div class="card-body">

                    <form action="{{ route('subscription.store') }}" method="POST" class="form-horizontal" id="payment-form">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('plan') ? ' has-error' : '' }}">
                           <div class="row">
                               <div class="col-md-3">
                                   <label for="plan" class="control-label">Plan</label>
                               </div>

                               <div class="col-md-9">
                                   <select name="plan" id="plan" class="form-control">
                                       @foreach ($plans as $plan)
                                           <option value="{{ $plan->gateway_id }}" {{ request('plan') === $plan->slug || old('plan') === $plan->gateway_id ? 'selected="selected"' : '' }}>{{ $plan->name }} (£{{ $plan->price }})</option>
                                       @endforeach
                                   </select>

                                   @if ($errors->has('plan'))
                                       <span class="help-block">
                                        <strong>{{ $errors->first('plan') }}</strong>
                                    </span>
                                   @endif
                               </div>
                           </div>
                        </div>

                        <div class="form-group{{ $errors->has('coupon') ? ' has-error' : '' }}">
                           <div class="row">
                               <div class="col-md-3">
                                   <label for="coupon" class="control-label">Coupon code</label>
                               </div>

                               <div class="col-md-9">
                                   <input type="text" name="coupon" id="coupon" class="form-control" value="{{ old('coupon') }}">

                                   @if ($errors->has('coupon'))
                                       <span class="help-block">
                                        <strong>{{ $errors->first('coupon') }}</strong>
                                    </span>
                                   @endif
                               </div>
                           </div>
                        </div>

                        <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-primary" id="pay">Pay</button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
@endsection

@section('scripts')
    <script src="https://checkout.stripe.com/checkout.js"></script>
    <script>
        let handler = StripeCheckout.configure({
            key: '{{ config('services.stripe.key') }}',
            locale: 'auto',
            token: function (token) {
                let form = $('#payment-form')

                $('#pay').prop('disabled', true)

                $('<input>').attr({
                    type: 'hidden',
                    name: 'token',
                    value: token.id
                }).appendTo(form)

                form.submit();
            }
        })

        $('#pay').click(function (e) {
            handler.open({
                name: 'Codecourse Ltd.',
                description: 'Membership',
                currency: 'gbp',
                key: '{{ config('services.stripe.key') }}',
                email: '{{ auth()->user()->email }}'
            })

            e.preventDefault();
        })
    </script>
@endsection

resources/views/subscription/plans/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <ul class="list-group">
                @foreach($plans as $plan)
                    <li class="list-group-item">
                        <a href="{{ route('subscription.index') }}?plan={{ $plan->slug }}">{{ $plan->name }} (£{{ $plan->price }})</a>
                    </li>
                @endforeach
                <li class="list-group-item">
                    <a href="{{ route('plans.teams.index') }}">Team plans</a>
                </li>
            </ul>
        </div>
    </div>
@endsection

resources/views/subscription/plans/teams/index.blade.php
@extends('layouts.app')

@section('content')
    <div class="row">
        <div class="col-md-6 offset-md-3">
            <ul class="list-group">
                @foreach($plans as $plan)
                    <li class="list-group-item">
                        <a href="{{ route('subscription.index') }}?plan={{ $plan->slug }}">{{ $plan->name }} (£{{ $plan->price }})</a>
                    </li>
                @endforeach
                <li class="list-group-item">
                    <a href="{{ route('plans.index') }}">User plans</a>
                </li>
            </ul>
        </div>
    </div>
@endsection